[env:ch32m030c8t7]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v
board = ch32m030c8t7
framework = arduino

; 串口配置
monitor_speed = 115200
board_build.mcu = ch32m030c8t7
board_build.f_cpu = 72000000L

; 上传配置
upload_protocol = wch-link
upload_speed = 500000

; 构建配置
build_flags = 
    -DCH32M030
    -DF_CPU=$BOARD_F_CPU

; 库依赖
lib_deps =
    Wire
    SPI
